In [0]:
# Databricks notebook source
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, udf,avg,min,max
from pyspark.sql.types import IntegerType,DoubleType
spark = SparkSession.builder.appName("groupBy - Assignment").getOrCreate()

# COMMAND ----------
df = spark.read.options(header='True', inferSchema='True').csv('/FileStore/tables/StudentData.csv')
df.show(5)

+---+------+----------------+------+-----+-----+--------------------+
|age|gender|            name|course| roll|marks|               email|
+---+------+----------------+------+-----+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB| 2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud|12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF|21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB|32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA|41487|   41|Claude Panos_Judi...|
+---+------+----------------+------+-----+-----+--------------------+
only showing top 5 rows

In [0]:
# Total # of students enrolled in each course
df.select(df.name,df.course).groupBy(df.course).count().show()

+------+-----+
|course|count|
+------+-----+
|    PF|  166|
|    DB|  157|
|   MVC|  157|
|   DSA|  176|
| Cloud|  192|
|   OOP|  152|
+------+-----+

In [0]:
# Total # of male and female enrolled in each course
df.select(df.gender,df.course).groupBy(df.course,df.gender).count().sort(df.course,df.gender).show()

+------+------+-----+
|course|gender|count|
+------+------+-----+
| Cloud|Female|  106|
| Cloud|  Male|   86|
|    DB|Female|   75|
|    DB|  Male|   82|
|   DSA|Female|   98|
|   DSA|  Male|   78|
|   MVC|Female|   71|
|   MVC|  Male|   86|
|   OOP|Female|   82|
|   OOP|  Male|   70|
|    PF|Female|   69|
|    PF|  Male|   97|
+------+------+-----+

In [0]:
# Total Marks achieved by each gender in each course

df.select(df.gender,df.course,df.marks).groupBy(df.course,df.gender).sum().sort(df.course,df.gender.desc()).show()

+------+------+----------+
|course|gender|sum(marks)|
+------+------+----------+
| Cloud|  Male|      5127|
| Cloud|Female|      6316|
|    DB|  Male|      5073|
|    DB|Female|      4197|
|   DSA|  Male|      4826|
|   DSA|Female|      6124|
|   MVC|  Male|      5241|
|   MVC|Female|      4344|
|   OOP|  Male|      4234|
|   OOP|Female|      4682|
|    PF|  Male|      5960|
|    PF|Female|      3973|
+------+------+----------+

In [0]:
# Display min,max and avg marks obtained by each age group.
df.select(df.age,df.marks).groupBy(df.age).agg(min('marks').alias('min_marks'),max('marks').alias('max_marks'),avg('marks').alias('avg_marks')).show()

+---+---------+---------+------------------+
|age|min_marks|max_marks|         avg_marks|
+---+---------+---------+------------------+
| 28|       20|       99|60.487854251012145|
| 29|       20|       99|59.715415019762844|
+---+---------+---------+------------------+